export const MODEL_1 = '?model=1'

// GRAPH
export const API_ENDPOINT_GRAPH = `${process.env.NEXT_PUBLIC_GRAPH_ENDPOINT}/api/graph`
export const API_ENDPOINT_GRAPH_MODEL_1 = `${API_ENDPOINT_GRAPH}${MODEL_1}`

export const API_ENDPOINT_GRAPH_NODES = `${API_ENDPOINT_GRAPH}/nodes${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID = `${API_ENDPOINT_GRAPH}/nodes/{id}${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID_EDGES = `${API_ENDPOINT_GRAPH}/nodes/{id}/edges${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID_EDGES_IN = `${API_ENDPOINT_GRAPH}/nodes/{id}/edges/in${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID_EDGES_OUT = `${API_ENDPOINT_GRAPH}/nodes/{id}/edges/out${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_CREATE = `${API_ENDPOINT_GRAPH}/nodes/create${MODEL_1}`

export const API_ENDPOINT_GRAPH_EDGES = `${API_ENDPOINT_GRAPH}/edges${MODEL_1}`
export const API_ENDPOINT_GRAPH_EDGES_ID = `${API_ENDPOINT_GRAPH}/edges/{id}${MODEL_1}`
export const API_ENDPOINT_GRAPH_EDGES_CREATE = `${API_ENDPOINT_GRAPH}/edges/create${MODEL_1}`

export const API_ENDPOINT_GRAPH_QUERY = `${API_ENDPOINT_GRAPH}/query`

// AUTH
export const API_ENDPOINT_AUTH = `${process.env.NEXT_PUBLIC_AUTH_API_ENDPOINT}/api/auth`

export const API_ENDPOINT_AUTH_SIGN_IN = `${API_ENDPOINT_AUTH}/login`
export const API_ENDPOINT_AUTH_TOKEN_REFRESH = `${API_ENDPOINT_AUTH}/token/refresh`

// STYLING
export const API_ENDPOINT_STYLING = `${process.env.NEXT_PUBLIC_STYLING_ENDPOINT}/api/ui/styling`

// COLLABORATION
export const API_ENDPOINT_COLLABORATION_GRAPH_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/notes`
export const API_ENDPOINT_COLLABORATION_GRAPH_NOTES_ID = `${API_ENDPOINT_COLLABORATION_GRAPH_NOTES}/{id}`
export const API_ENDPOINT_COLLABORATION_GRAPH_NOTES_CREATE = `${API_ENDPOINT_COLLABORATION_GRAPH_NOTES}/create`

export const API_ENDPOINT_COLLABORATION_NODE_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/nodes/notes`
export const API_ENDPOINT_COLLABORATION_NODE_ID_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/nodes/{node_id}/notes`
export const API_ENDPOINT_COLLABORATION_NODE_ID_NOTES_ID = `${API_ENDPOINT_COLLABORATION_NODE_ID_NOTES}/{note_id}`
export const API_ENDPOINT_COLLABORATION_NODE_ID_NOTES_CREATE = `${API_ENDPOINT_COLLABORATION_NODE_ID_NOTES}/create`

export const API_ENDPOINT_COLLABORATION_EDGE_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/edges/notes`
export const API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/edges/{edge_id}/notes`
export const API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES_ID = `${API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES}/{note_id}`
export const API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES_CREATE = `${API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES}/create`

// ONTOLOGY
export const API_ENDPOINT_ONTOLOGY = `${process.env.NEXT_PUBLIC_ONTOLOGY_ENDPOINT}/api/ontology`

export const API_ENDPOINT_ONTOLOGY_PROPERTIES = `${API_ENDPOINT_ONTOLOGY}/properties`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS = `${API_ENDPOINT_ONTOLOGY_PROPERTIES}/annotations`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS_IRI = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS}/annotation?iri={iri}`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS_ID = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS}/{id}`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS = `${API_ENDPOINT_ONTOLOGY_PROPERTIES}/objects`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS_IRI = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS}/object?iri={iri}`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS_ID = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS}/{id}`

export const API_ENDPOINT_ONTOLOGY_CLASS = `${API_ENDPOINT_ONTOLOGY}/classes`
export const API_ENDPOINT_ONTOLOGY_CLASS_ID = `${API_ENDPOINT_ONTOLOGY_CLASS}/{id}`
export const API_ENDPOINT_ONTOLOGY_CLASS_IRI = `${API_ENDPOINT_ONTOLOGY_CLASS}/class?iri={iri}`

export const API_ENDPOINT_ONTOLOGY_TRIPLE = `${API_ENDPOINT_ONTOLOGY}/triples`
export const API_ENDPOINT_ONTOLOGY_TRIPLE_ID = `${API_ENDPOINT_ONTOLOGY_TRIPLE}/{id}`
