export const ENDPOINT_URL = process.env.NEXT_PUBLIC_API_ENDPOINT
export const COLLABORATION_URL = process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT
export const API_COLLABORATION_ENDPOINT = `${COLLABORATION_URL}/api`
export const API_ENDPOINT = `${ENDPOINT_URL}/api`

export const GET_ONTOLOGY = `${API_ENDPOINT}/ontology`
export const GET_GRAPH = `${API_ENDPOINT}/graph`
export const GET_COLLABORATION_GRAPH = `${API_COLLABORATION_ENDPOINT}/graph`

export const MODEL_1 = '?model=1'

// GRAPH
export const API_ENDPOINT_GRAPH = `${process.env.NEXT_PUBLIC_GRAPH_ENDPOINT}/api/graph`
export const API_ENDPOINT_GRAPH_MODEL_1 = `${API_ENDPOINT_GRAPH}${MODEL_1}`

export const API_ENDPOINT_GRAPH_NODES = `${API_ENDPOINT_GRAPH}/nodes${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID = `${API_ENDPOINT_GRAPH}/nodes/{id}${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID_EDGES = `${API_ENDPOINT_GRAPH}/nodes/{id}/edges${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID_EDGES_IN = `${API_ENDPOINT_GRAPH}/nodes/{id}/edges/in${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_ID_EDGES_OUT = `${API_ENDPOINT_GRAPH}/nodes/{id}/edges/out${MODEL_1}`
export const API_ENDPOINT_GRAPH_NODES_CREATE = `${API_ENDPOINT_GRAPH}/nodes/create${MODEL_1}`

export const API_ENDPOINT_GRAPH_EDGES = `${API_ENDPOINT_GRAPH}/edges${MODEL_1}`
export const API_ENDPOINT_GRAPH_EDGES_ID = `${API_ENDPOINT_GRAPH}/edges/{id}${MODEL_1}`
export const API_ENDPOINT_GRAPH_EDGES_CREATE = `${API_ENDPOINT_GRAPH}/edges/create${MODEL_1}`

export const API_ENDPOINT_GRAPH_QUERY = `${API_ENDPOINT_GRAPH}/query`

// AUTH
export const API_ENDPOINT_AUTH = `${process.env.NEXT_PUBLIC_AUTH_API_ENDPOINT}/api/auth`

export const API_ENDPOINT_AUTH_SIGN_IN = `${API_ENDPOINT_AUTH}/login`
export const API_ENDPOINT_AUTH_TOKEN_REFRESH = `${API_ENDPOINT_AUTH}/token/refresh`

// STYLING
export const API_ENDPOINT_STYLING = `${process.env.NEXT_PUBLIC_STYLING_ENDPOINT}/api/ui/styling`

// COLLABORATION
export const API_ENDPOINT_COLLABORATION_GRAPH_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/notes`
export const API_ENDPOINT_COLLABORATION_GRAPH_NOTES_ID = `${API_ENDPOINT_COLLABORATION_GRAPH_NOTES}/{id}`
export const API_ENDPOINT_COLLABORATION_GRAPH_NOTES_CREATE = `${API_ENDPOINT_COLLABORATION_GRAPH_NOTES}/create`

export const API_ENDPOINT_COLLABORATION_NODE_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/nodes/notes`
export const API_ENDPOINT_COLLABORATION_NODE_ID_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/nodes/{node_id}/notes`
export const API_ENDPOINT_COLLABORATION_NODE_ID_NOTES_ID = `${API_ENDPOINT_COLLABORATION_NODE_ID_NOTES}/{note_id}`
export const API_ENDPOINT_COLLABORATION_NODE_ID_NOTES_CREATE = `${API_ENDPOINT_COLLABORATION_NODE_ID_NOTES}/create`

export const API_ENDPOINT_COLLABORATION_EDGE_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/edges/notes`
export const API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES = `${process.env.NEXT_PUBLIC_COLLABORATION_API_ENDPOINT}/api/graph/edges/{edge_id}/notes`
export const API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES_ID = `${API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES}/{note_id}`
export const API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES_CREATE = `${API_ENDPOINT_COLLABORATION_EDGE_ID_NOTES}/create`

// ONTOLOGY
export const API_ENDPOINT_ONTOLOGY = `${process.env.NEXT_PUBLIC_ONTOLOGY_ENDPOINT}/api/ontology`

export const API_ENDPOINT_ONTOLOGY_PROPERTIES = `${API_ENDPOINT_ONTOLOGY}/properties`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS = `${API_ENDPOINT_ONTOLOGY_PROPERTIES}/annotations`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS_IRI = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS}/annotation?iri={iri}`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS_ID = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_ANNOTATIONS}/{id}`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS = `${API_ENDPOINT_ONTOLOGY_PROPERTIES}/objects`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS_IRI = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS}/object?iri={iri}`
export const API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS_ID = `${API_ENDPOINT_ONTOLOGY_PROPERTIES_OBJECTS}/{id}`

export const GET_GRAPH_NOTES = `${GET_COLLABORATION_GRAPH}/notes`
export const GET_GRAPH_NOTE = `${GET_COLLABORATION_GRAPH}/notes/{id}`
export const POST_CREATE_GRAPH_NOTE = `${GET_COLLABORATION_GRAPH}/notes/create`
export const PATCH_UPDATE_GRAPH_NOTE = `${GET_COLLABORATION_GRAPH}/notes/{id}`
export const DELETE_GRAPH_NOTE = `${GET_COLLABORATION_GRAPH}/notes/{id}`

export const GET_NODES_NOTES = `${GET_COLLABORATION_GRAPH}/nodes/notes`
export const GET_NODE_NOTES = `${GET_COLLABORATION_GRAPH}/nodes/{node_id}/notes`
export const GET_NODE_NOTE = `${GET_COLLABORATION_GRAPH}/nodes/{node_id}/notes/{id}`
export const POST_CREATE_NODE_NOTE = `${GET_COLLABORATION_GRAPH}/nodes/{node_id}/notes/create`
export const PATCH_UPDATE_NODE_NOTE = `${GET_COLLABORATION_GRAPH}/nodes/{node_id}/notes/{id}`
export const DELETE_NODE_NOTE = `${GET_COLLABORATION_GRAPH}/nodes/{node_id}/notes/{id}`

export const GET_EDGES_NOTES = `${GET_COLLABORATION_GRAPH}/edges/notes`
export const GET_EDGE_NOTES = `${GET_COLLABORATION_GRAPH}/edges/{edge_id}/notes`
export const GET_EDGE_NOTE = `${GET_COLLABORATION_GRAPH}/edges/{edge_id}/notes/{id}`
export const POST_CREATE_EDGE_NOTE = `${GET_COLLABORATION_GRAPH}/edges/{edge_id}/notes/create`
export const PATCH_UPDATE_EDGE_NOTE = `${GET_COLLABORATION_GRAPH}/edges/{edge_id}/notes/{id}`
export const DELETE_EDGE_NOTE = `${GET_COLLABORATION_GRAPH}/edges/{edge_id}/notes/{id}`

export const AUTH_SIGN_IN = `${API_ENDPOINT}/auth/login`
export const API_ENDPOINT_ONTOLOGY_CLASS = `${API_ENDPOINT_ONTOLOGY}/classes`
export const API_ENDPOINT_ONTOLOGY_CLASS_ID = `${API_ENDPOINT_ONTOLOGY_CLASS}/{id}`
export const API_ENDPOINT_ONTOLOGY_CLASS_IRI = `${API_ENDPOINT_ONTOLOGY_CLASS}/class?iri={iri}`

export const API_ENDPOINT_ONTOLOGY_TRIPLE = `${API_ENDPOINT_ONTOLOGY}/triples`
export const API_ENDPOINT_ONTOLOGY_TRIPLE_ID = `${API_ENDPOINT_ONTOLOGY_TRIPLE}/{id}`
