export const CUSTOM_QUERIES_LS = 'gv-custom=queries'
export const STYLING_LS = 'gv-styling'
export const GRAPH_VERSIONS_LS = 'gv-graph-versions'
export const ANALYTICS_COOKIE = 'cookie_marketing'
export const PREFERENCES_COOKIES = 'cookie_preferences'
export const I18N_LANGUAGE = 'i18n_lang'
