export const OPERATION_TYPE_ADD = 'add'
export const OPERATION_TYPE_DELETE = 'delete'
export const OPERATION_TYPE_UPDATE = 'update'
export const OPERATION_TYPE_PUSH = 'push'
export const OPERATION_TYPE_PUSH_UNIQUE = 'pushUnique'
export const OPERATION_TYPE_TOGGLE = 'toggle'
export const OPERATION_TYPE_ARRAY_DELETE = 'arrayDelete'
export const OPERATION_TYPE_OBJECT_ADD = 'objectAdd'
