export const NETWORK_GRAPH_VIEW = 'networkGraphView'
export const TABLE_VIEW = 'tableView'

export const SIDEBAR_VIEW_GRAPHS = 'networkGraphs'
export const SIDEBAR_VIEW_SEARCH = 'search'
export const SIDEBAR_VIEW_NODES_SELECTION = 'nodesSelection'
export const SIDEBAR_VIEW_EDGES_SELECTION = 'edgesSelection'
export const SIDEBAR_VIEW_NEIGHBOURHOOD = 'nodeNeighbourhood'
export const SIDEBAR_VIEW_SHORTEST_PATH = 'shortestPath'
export const SIDEBAR_VIEW_SETTINGS = 'settings'
export const SIDEBAR_VIEW_EXPORT = 'export'
