export const IS_SEARCH_VISIBLE = process.env.NEXT_PUBLIC_SEARCH === 'true'
export const IS_GRAPHS_VISIBLE = process.env.NEXT_PUBLIC_GRAPHS === 'true'
export const IS_GRAPH_OPTIONS_VISIBLE = process.env.NEXT_PUBLIC_GRAPH_OPTIONS === 'true'
export const IS_ELEMENT_SELECTION_VISIBLE = process.env.NEXT_PUBLIC_SELECTION === 'true'
export const IS_ELEMENTS_FILTER_VISIBLE = process.env.NEXT_PUBLIC_FILTERS === 'true'
export const IS_EDGES_FILTER_VISIBLE = process.env.NEXT_PUBLIC_FILTERS === 'true'
export const IS_BOUNDING_BOX_VISIBLE = process.env.NEXT_PUBLIC_BOUNDING_BOX === 'true'
export const IS_NEIGHBOURHOOD_VISIBLE = process.env.NEXT_PUBLIC_NEIGHBOURHOOD === 'true'
export const IS_SHORTEST_PATH_VISIBLE = process.env.NEXT_PUBLIC_SHORTEST_PATH === 'true'
export const IS_CUSTOM_QUERY_VISIBLE = process.env.NEXT_PUBLIC_CUSTOM_QUERY === 'true'
export const IS_PHYSICS_SETTINGS_VISIBLE = process.env.NEXT_PUBLIC_PHYSICS_SETTINGS === 'true'
export const IS_STYLING_VISIBLE = process.env.NEXT_PUBLIC_STYLING === 'true'
export const IS_NOTES_VISIBLE = process.env.NEXT_PUBLIC_NOTES === 'true'
export const IS_SYNONIMS_VISIBLE = process.env.NEXT_PUBLIC_SYNONIMS === 'true'
export const IS_EXPORT_VISIBLE = process.env.NEXT_PUBLIC_EXPORT === 'true'
export const IS_EDIT_ONTOLOGY_VISIBLE = process.env.NEXT_PUBLIC_EDIT_ONTOLOGY === 'true'
export const IS_SHOW_TOUR_VISIBLE = process.env.NEXT_PUBLIC_SHOW_TOUR === 'true'

export const SIDEBAR_VIEW_ENTRY_SEARCH = 'search'
export const SIDEBAR_VIEW_GRAPHS = 'networkGraphs'
export const SIDEBAR_VIEW_GRAPH_OPTIONS = 'networkGraphOptions'
export const SIDEBAR_VIEW_SYNONYMS = 'synonyms'
export const SIDEBAR_VIEW_ELEMENTS_SELECTION = 'elementsSelection'
export const SIDEBAR_VIEW_ELEMENTS_FILTER = 'elementsFilter'
export const SIDEBAR_VIEW_EDGES_FILTER = 'edgesFilter'
export const SIDEBAR_VIEW_BOUNDING_BOX = 'boundingBox'
export const SIDEBAR_VIEW_NEIGHBOURHOOD = 'nodeNeighbourhood'
export const SIDEBAR_VIEW_SHORTEST_PATH = 'shortestPath'
export const SIDEBAR_VIEW_STYLING = 'styling'
export const SIDEBAR_VIEW_NOTES = 'notes'
export const SIDEBAR_VIEW_EXPORT = 'export'
export const SIDEBAR_VIEW_CUSTOM_QUERY = 'customQuery'
export const SIDEBAR_VIEW_EDIT_ONTOLOGY = 'editOntology'

export const NETWORK_VIEW_DATATABLE = 'datatable'
export const NETWORK_VIEW_GRAPH = 'graph'
