/* eslint max-len:0 */
import structuredSearchElement from '../../../utils/structuredSearch/structuredSearchElement'
import { classesFromApi } from '../../fixtures/classesFromApi'
import { objectPropertiesFromApi } from '../../fixtures/objectPropertiesFromApi'
import store from '../../../store'
import getNodeIds from '../../../utils/nodesEdgesUtils/getNodeIds'
import getEdgeIds from '../../../utils/nodesEdgesUtils/getEdgeIds'
import { OPERATION_TYPE_UPDATE } from '../../../constants/store'

const updateStoreValue = jest.fn()

store.getState = jest.fn().mockImplementation(() => ({
  classesFromApi,
  objectPropertiesFromApi,
}))

jest.mock('../../../utils/nodesEdgesUtils/getNodeIds')
jest.mock('../../../utils/nodesEdgesUtils/getEdgeIds')

getNodeIds.mockImplementation(() => Object.keys(classesFromApi))
getEdgeIds.mockImplementation(() => Object.keys(objectPropertiesFromApi))

describe('structuredSearchElement', () => {
  afterEach(() => {
    jest.clearAllMocks()
  })

  it('should not call updateStoreValue when empty filters', async () => {
    const queryLogic = 'and'
    const filters = []

    await structuredSearchElement({
      filters,
      queryLogic,
      updateStoreValue,
    })

    expect(updateStoreValue).toHaveBeenCalledTimes(0)
  })

  it('should not call updateStoreValue when filters with no value', async () => {
    const queryLogic = 'and'
    const filters = [{
      property: 'rdfAbout',
      value: ''
    }, {
      property: 'rdfsLabel',
      value: ''
    }]

    await structuredSearchElement({
      filters,
      queryLogic,
      updateStoreValue,
    })

    expect(updateStoreValue).toHaveBeenCalledTimes(0)
  })

  it('should return correct results when AND query', async () => {
    const queryLogic = 'and'
    const filters = [{
      property: 'rdfsLabel',
      value: 'ro'
    }, {
      property: 'rdfsLabel',
      value: 'ad'
    }]

    await structuredSearchElement({
      filters,
      queryLogic,
      updateStoreValue,
    })

    expect(updateStoreValue).toHaveBeenCalledWith(
      ['structuredSelection'], OPERATION_TYPE_UPDATE, {
        103: {
          'Business Area': 'Maintain Construct Plan',
          'Data Source': 'Confirm',
          id: '103',
          label: 'Road Restraint',
          name: 'Road Restraint',
          nodeId: 103,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RBBDxx5ZaIbg5ASqGAeyKGg',
          rdfsLabel: 'Road Restraint',
          skosDefinition: 'Assets designed to contain, slow down, and stop errant vehicles, and to protect other Assets and Customers from errant Vehicles.',
          type: 'node',
          upperOntology: false,
          userDefined: false
        },
        128: {
          'Business Area': 'Maintain Construct Operate Plan',
          'Data Source': 'NTIS Confirm',
          Subdomain: 'NTIS',
          id: '128',
          label: 'Roadside Operational Technology',
          name: 'Roadside Operational Technology',
          nodeId: 128,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RCOdkBizz0dWtRTEjZSfqP8',
          rdfsLabel: 'Roadside Operational Technology',
          skosDefinition: 'Items involved in the digital capture, transfer, or analysis of information specifically related to the Strategic Road Network Asset.',
          skosExample: 'Speed Camera',
          type: 'node',
          upperOntology: false,
          userDefined: false
        },
        187: {
          'Business Area': 'Maintain Construct',
          Subdomain: 'Construction phase',
          id: '187',
          label: 'Road Safety Measure',
          name: 'Road Safety Measure',
          nodeId: 187,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/Rigjqi5P4ZscabU1Pot3hK',
          rdfsLabel: 'Road Safety Measure',
          skosDefinition: 'Methods and measures used to prevent road users and workers from being killed or seriously injured.',
          type: 'node',
          upperOntology: false,
          userDefined: false
        },
        73: {
          'Business Area': 'Maintain Plan Operate Construct Plan',
          'Data Source': 'Confirm',
          Subdomain: 'Construction phase',
          id: '73',
          label: 'Strategic Road Network Asset',
          name: 'Strategic Road Network Asset',
          nodeId: 73,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R9H3QGGtwC0XhV4Mfk6Ceep',
          rdfsLabel: 'Strategic Road Network Asset',
          skosDefinition: 'Assets that, when combined, create and support the physical network of roads managed by the Licence Holder known as the Strategic Road Network Asset (which are represented by a Network Model).',
          type: 'node',
          upperOntology: false,
          userDefined: false
        }
      }
    )
  })

  it('should return correct results when OR query', async () => {
    const queryLogic = 'or'
    const filters = [{
      property: 'rdfsLabel',
      value: 'ro'
    }, {
      property: 'rdfsLabel',
      value: 'ad'
    }]

    await structuredSearchElement({
      filters,
      queryLogic,
      updateStoreValue,
    })

    expect(updateStoreValue).toHaveBeenCalledWith(
      ['structuredSelection'], OPERATION_TYPE_UPDATE, {
        103: {
          'Business Area': 'Maintain Construct Plan',
          'Data Source': 'Confirm',
          id: '103',
          label: 'Road Restraint',
          name: 'Road Restraint',
          nodeId: 103,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RBBDxx5ZaIbg5ASqGAeyKGg',
          rdfsLabel: 'Road Restraint',
          skosDefinition: 'Assets designed to contain, slow down, and stop errant vehicles, and to protect other Assets and Customers from errant Vehicles.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1072: {
          edgeId: 1072,
          from: '107',
          id: '1072',
          label: 'Advised by',
          rdfAbout: 'http://webprotege.stanford.edu/R7V7p8sdl5TpSs0cd7gZvqr',
          rdfsLabel: 'Advised by',
          role: 'Advised by',
          to: '128',
          type: 'edge',
          userDefined: false,
        },
        108: {
          'Business Area': 'Maintain Construct Plan',
          'Data Source': 'Confirm',
          id: '108',
          label: 'Environmental',
          name: 'Environmental',
          nodeId: 108,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RBKQgaabYcnNDy5hL7YKCKt',
          rdfsLabel: 'Environmental',
          skosComment: "Environmental is broadly split into three parts: Organisms (plants, animals, vegetation, grasslands), Cultural Heritage sites, and Noise Barriers. \"Environmental\" as a word seems to relate more closely with the Organisms meaning. As there are three distinct meanings, these were all defined separately and combined to create the overall definition of \"Environmental\" above. If either of the three areas get moved under a different heading (Entity) then the definitions can simply be cut and pasted into that new heading's (Entity's) definition.",
          skosDefinition: 'Plants, animals, and their habitats around the Strategic Road Network Asset; as well as Cultural Heritage and Art sites around the Strategic Road Network Asset; and Noise Barriers.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1092: {
          edgeId: 1092,
          from: '109',
          id: '1092',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '12',
          type: 'edge',
          userDefined: false,
        },
        11: {
          edgeId: 11,
          from: '1',
          id: '11',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '177',
          type: 'edge',
          userDefined: false,
        },
        1102: {
          edgeId: 1102,
          from: '110',
          id: '1102',
          label: 'Advised by',
          rdfAbout: 'http://webprotege.stanford.edu/R7V7p8sdl5TpSs0cd7gZvqr',
          rdfsLabel: 'Advised by',
          role: 'Advised by',
          to: '130',
          type: 'edge',
          userDefined: false,
        },
        1132: {
          edgeId: 1132,
          from: '113',
          id: '1132',
          label: 'Obtained through',
          rdfAbout: 'http://webprotege.stanford.edu/RDgkQlvQbb2skaXpfhIEAp8',
          rdfsLabel: 'Obtained through',
          role: 'Obtained through',
          to: '9',
          type: 'edge',
          userDefined: false,
        },
        115: {
          'Business Area': 'Construct',
          id: '115',
          label: 'Progress',
          name: 'Progress',
          nodeId: 115,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RBeMHRpPtIj9w4fNQv66hnI',
          rdfsLabel: 'Progress',
          skosDefinition: 'The degree of gradual improvement of a process or Project.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1193: {
          edgeId: 1193,
          from: '119',
          id: '1193',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '199',
          type: 'edge',
          userDefined: false,
        },
        128: {
          'Business Area': 'Maintain Construct Operate Plan',
          'Data Source': 'NTIS Confirm',
          Subdomain: 'NTIS',
          id: '128',
          label: 'Roadside Operational Technology',
          name: 'Roadside Operational Technology',
          nodeId: 128,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RCOdkBizz0dWtRTEjZSfqP8',
          rdfsLabel: 'Roadside Operational Technology',
          skosDefinition: 'Items involved in the digital capture, transfer, or analysis of information specifically related to the Strategic Road Network Asset.',
          skosExample: 'Speed Camera',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1282: {
          edgeId: 1282,
          from: '128',
          id: '1282',
          label: 'Controlled by',
          rdfAbout: 'http://webprotege.stanford.edu/R8XmPwbVWaRiEyUv3kxunaF',
          rdfsLabel: 'Controlled by',
          role: 'Controlled by',
          to: '56',
          type: 'edge',
          userDefined: false,
        },
        1283: {
          edgeId: 1283,
          from: '128',
          id: '1283',
          label: 'Controlled by',
          rdfAbout: 'http://webprotege.stanford.edu/R8XmPwbVWaRiEyUv3kxunaF',
          rdfsLabel: 'Controlled by',
          role: 'Controlled by',
          to: '199',
          type: 'edge',
          userDefined: false,
        },
        136: {
          'Business Area': 'Maintain Plan Operate Construct',
          'Data Source': 'Confirm',
          id: '136',
          label: 'Carriageway Control',
          name: 'Carriageway Control',
          nodeId: 136,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RCrgRyMOzbaY6vxlnONgyzo',
          rdfsLabel: 'Carriageway Control',
          skosDefinition: 'Assets used to inform, direct, and control Traffic (Vehicles on the Strategic Road Network Asset) and form boundaries within the Strategic Road Network Asset.',
          skosExample: 'Post (Signs), Post (Traffic Signal), Block Wall, Fence, Cattle Grid',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1453: {
          edgeId: 1453,
          from: '145',
          id: '1453',
          label: 'Performed from',
          rdfAbout: 'http://webprotege.stanford.edu/RC48Hic1INaQShlkSyb6ZIx',
          rdfsLabel: 'Performed from',
          role: 'Performed from',
          to: '87',
          type: 'edge',
          userDefined: false,
        },
        150: {
          'Business Area': 'Operate Design Construct Plan Communications',
          Subdomain: 'Handover',
          id: '150',
          label: 'Project Phase',
          name: 'Project Phase',
          nodeId: 150,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RDUwHG4VnwQTyDDhhsWSwgS',
          rdfsLabel: 'Project Phase',
          skosComment: 'The 3D framework is used in Operations and contains the stages:\n1. Scheme Identification\n2. Options Assessment\n3. Preliminary Design\n4. Detailed Design\n5. Commercial Pricing\n6. Construction\n7. Closeout',
          skosDefinition: 'Goal-oriented collection of activities within a Project that ends at a milestone and are defined within a framework, where each phase can be divided into sub-phases.',
          skosExample: 'Pre-project, Options phase, Development phase, Construction phase',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1505: {
          edgeId: 1505,
          from: '150',
          id: '1505',
          label: 'Controlled by',
          rdfAbout: 'http://webprotege.stanford.edu/R8XmPwbVWaRiEyUv3kxunaF',
          rdfsLabel: 'Controlled by',
          role: 'Controlled by',
          to: '190',
          type: 'edge',
          userDefined: false,
        },
        1524: {
          edgeId: 1524,
          from: '152',
          id: '1524',
          label: 'Paid through',
          rdfAbout: 'http://webprotege.stanford.edu/RCO41EY55jxxkXEYAsRnzul',
          rdfsLabel: 'Paid through',
          role: 'Paid through',
          to: '27',
          type: 'edge',
          userDefined: false,
        },
        1531: {
          edgeId: 1531,
          from: '153',
          id: '1531',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '177',
          type: 'edge',
          userDefined: false,
        },
        1532: {
          edgeId: 1532,
          from: '153',
          id: '1532',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '68',
          type: 'edge',
          userDefined: false,
        },
        1572: {
          edgeId: 1572,
          from: '157',
          id: '1572',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '134',
          type: 'edge',
          userDefined: false,
        },
        162: {
          edgeId: 162,
          from: '16',
          id: '162',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        168: {
          'Business Area': 'Maintain Design Plan Finance Operate Construct Communications',
          Subdomain: 'Pre-project phase, Construction phase',
          id: '168',
          label: 'Project',
          name: 'Project',
          nodeId: 168,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RJVpffoomVWohIDaJCykd9',
          rdfsLabel: 'Project',
          skosDefinition: 'A time-bound undertaking of the Licence Holder (and Suppliers) to deliver a defined outcome to their organisation, stakeholders, or the general public.',
          skosExample: 'The road that needs to be built between the M25 and xyz in order to connect London to Inverness as part of a wider Programme.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1682: {
          edgeId: 1682,
          from: '168',
          id: '1682',
          label: 'Advised by',
          rdfAbout: 'http://webprotege.stanford.edu/R7V7p8sdl5TpSs0cd7gZvqr',
          rdfsLabel: 'Advised by',
          role: 'Advised by',
          to: '68',
          type: 'edge',
          userDefined: false,
        },
        1683: {
          edgeId: 1683,
          from: '168',
          id: '1683',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '171',
          type: 'edge',
          userDefined: false,
        },
        1686: {
          edgeId: 1686,
          from: '168',
          id: '1686',
          label: 'Proposed in',
          rdfAbout: 'http://webprotege.stanford.edu/R4I2v4Y7su3Adf0Vcj6TWd',
          rdfsLabel: 'Proposed in',
          role: 'Proposed in',
          to: '132',
          type: 'edge',
          userDefined: false,
        },
        184: {
          'Business Area': 'Maintain',
          id: '184',
          label: 'Product',
          name: 'Product',
          nodeId: 184,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/Rf8re1EdmLU47EIlLtCpzx',
          rdfsLabel: 'Product',
          skosDefinition: 'A software package that performs a specific function directly for an end user or, in some cases, for another Product.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1854: {
          edgeId: 1854,
          from: '185',
          id: '1854',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '70',
          type: 'edge',
          userDefined: false,
        },
        187: {
          'Business Area': 'Maintain Construct',
          Subdomain: 'Construction phase',
          id: '187',
          label: 'Road Safety Measure',
          name: 'Road Safety Measure',
          nodeId: 187,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/Rigjqi5P4ZscabU1Pot3hK',
          rdfsLabel: 'Road Safety Measure',
          skosDefinition: 'Methods and measures used to prevent road users and workers from being killed or seriously injured.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1892: {
          edgeId: 1892,
          from: '189',
          id: '1892',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '12',
          type: 'edge',
          userDefined: false,
        },
        191: {
          'Business Area': 'Operate Design Construct Plan Maintain',
          id: '191',
          label: 'Environmental Condition',
          name: 'Environmental Condition',
          nodeId: 191,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RmVBgJPMOQ5Amchla0VZUw',
          rdfsLabel: 'Environmental Condition',
          skosDefinition: 'A measure of how the environment proximate to the Network is developing or declining.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1912: {
          edgeId: 1912,
          from: '191',
          id: '1912',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        1923: {
          edgeId: 1923,
          from: '192',
          id: '1923',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '107',
          type: 'edge',
          userDefined: false,
        },
        193: {
          'Business Area': 'Maintain Operate',
          Subdomain: 'NTIS',
          id: '193',
          label: 'Control Centre',
          name: 'Control Centre',
          nodeId: 193,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RnMK2vS5olvsw9Krge2Ymj',
          rdfsLabel: 'Control Centre',
          skosDefinition: 'A facility, used by the License Holder, which permits the coordinated and deliberate monitoring and regulation of service on the Network.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        1961: {
          edgeId: 1961,
          from: '196',
          id: '1961',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '193',
          type: 'edge',
          userDefined: false,
        },
        1982: {
          edgeId: 1982,
          from: '198',
          id: '1982',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        1985: {
          edgeId: 1985,
          from: '198',
          id: '1985',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '12',
          type: 'edge',
          userDefined: false,
        },
        1992: {
          edgeId: 1992,
          from: '199',
          id: '1992',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '64',
          type: 'edge',
          userDefined: false,
        },
        2: {
          'Business Area': 'Maintain Plan',
          id: '2',
          label: 'Programme',
          name: 'Programme',
          nodeId: 2,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R0qk59fxFmgNbyUncZoU8M',
          rdfsLabel: 'Programme',
          skosComment: 'A strategic goal that is achieved through a number of projects.',
          skosDefinition: 'A collection of projects or tasks undertaken to realise a strategic goal.',
          skosExample: 'Develop connectivity between London and Inverness.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        20: {
          id: '20',
          label: 'MetaData',
          name: 'MetaData',
          nodeId: 20,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R7QCWoGMafG9zhjDYABQQgm',
          rdfsLabel: 'MetaData',
          skosDefinition: 'Data about data.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        2022: {
          edgeId: 2022,
          from: '202',
          id: '2022',
          label: 'Proposed in',
          rdfAbout: 'http://webprotege.stanford.edu/R4I2v4Y7su3Adf0Vcj6TWd',
          rdfsLabel: 'Proposed in',
          role: 'Proposed in',
          to: '150',
          type: 'edge',
          userDefined: false,
        },
        232: {
          edgeId: 232,
          from: '23',
          id: '232',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '152',
          type: 'edge',
          userDefined: false,
        },
        35: {
          'Business Area': 'Operate',
          'Data Source': 'Confirm NOMS',
          Subdomain: 'Confirm',
          Synonym: 'Polyline',
          id: '35',
          label: 'Route',
          name: 'Route',
          nodeId: 35,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R7pIV91w7fTKppAHSmrz8n',
          rdfsLabel: 'Route',
          skosDefinition: 'A potential way or course to get from one Node to another.',
          skosExample: 'Alternate Route',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        411: {
          edgeId: 411,
          from: '41',
          id: '411',
          label: 'Obtained through',
          rdfAbout: 'http://webprotege.stanford.edu/RDgkQlvQbb2skaXpfhIEAp8',
          rdfsLabel: 'Obtained through',
          role: 'Obtained through',
          to: '23',
          type: 'edge',
          userDefined: false,
        },
        482: {
          edgeId: 482,
          from: '48',
          id: '482',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        494: {
          edgeId: 494,
          from: '49',
          id: '494',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        522: {
          edgeId: 522,
          from: '52',
          id: '522',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        56: {
          'Business Area': 'Maintain Operate Design Finance Plan Communications',
          'Data Source': 'Estates Confirm NOMS',
          Subdomain: 'Estates, NTIS, Options phase, Confirm',
          Type: 'Employee, External Staff, Administrator, Analyst, Internal Customer, Project Manager, Sponsor, User, Action Officer',
          id: '56',
          label: 'Role',
          name: 'Role',
          nodeId: 56,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R8QQzkUbCD5WRXDQQSl0vX8',
          rdfsLabel: 'Role',
          skosDefinition: 'The function assumed or part played by a person or thing in a particular situation.',
          skosExample: 'Action officer, Auditor, Technician',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        563: {
          edgeId: 563,
          from: '56',
          id: '563',
          label: 'Performed from',
          rdfAbout: 'http://webprotege.stanford.edu/RC48Hic1INaQShlkSyb6ZIx',
          rdfsLabel: 'Performed from',
          role: 'Performed from',
          to: '26',
          type: 'edge',
          userDefined: false,
        },
        633: {
          edgeId: 633,
          from: '63',
          id: '633',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '193',
          type: 'edge',
          userDefined: false,
        },
        72: {
          edgeId: 72,
          from: '7',
          id: '72',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        721: {
          edgeId: 721,
          from: '72',
          id: '721',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '68',
          type: 'edge',
          userDefined: false,
        },
        723: {
          edgeId: 723,
          from: '72',
          id: '723',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '199',
          type: 'edge',
          userDefined: false,
        },
        724: {
          edgeId: 724,
          from: '72',
          id: '724',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '199',
          type: 'edge',
          userDefined: false,
        },
        729: {
          edgeId: 729,
          from: '72',
          id: '729',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '119',
          type: 'edge',
          userDefined: false,
        },
        73: {
          'Business Area': 'Maintain Plan Operate Construct Plan',
          'Data Source': 'Confirm',
          Subdomain: 'Construction phase',
          id: '73',
          label: 'Strategic Road Network Asset',
          name: 'Strategic Road Network Asset',
          nodeId: 73,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R9H3QGGtwC0XhV4Mfk6Ceep',
          rdfsLabel: 'Strategic Road Network Asset',
          skosDefinition: 'Assets that, when combined, create and support the physical network of roads managed by the Licence Holder known as the Strategic Road Network Asset (which are represented by a Network Model).',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        735: {
          edgeId: 735,
          from: '73',
          id: '735',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '168',
          type: 'edge',
          userDefined: false,
        },
        736: {
          edgeId: 736,
          from: '73',
          id: '736',
          label: 'Obtained through',
          rdfAbout: 'http://webprotege.stanford.edu/RDgkQlvQbb2skaXpfhIEAp8',
          rdfsLabel: 'Obtained through',
          role: 'Obtained through',
          to: '9',
          type: 'edge',
          userDefined: false,
        },
        762: {
          edgeId: 762,
          from: '76',
          id: '762',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '107',
          type: 'edge',
          userDefined: false,
        },
        772: {
          edgeId: 772,
          from: '77',
          id: '772',
          label: 'Implemented through',
          rdfAbout: 'http://webprotege.stanford.edu/RbjcXDTrplTouTeWRoMMe7',
          rdfsLabel: 'Implemented through',
          role: 'Implemented through',
          to: '183',
          type: 'edge',
          userDefined: false,
        },
        79: {
          'Business Area': 'Maintain Design Finance Construct',
          id: '79',
          label: 'Project Document',
          name: 'Project Document',
          nodeId: 79,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R9WIxkbvxYbhp8NthzYsXSx',
          rdfsLabel: 'Project Document',
          skosDefinition: 'Document related to the running of a Project.',
          skosExample: 'Project Control Document',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        84: {
          'Business Area': 'Operate',
          'Data Source': 'NTIS',
          Subdomain: 'NTIS',
          id: '84',
          label: 'Headway',
          name: 'Headway',
          nodeId: 84,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R9r0DVvDkFW6GmN4bDUNsyl',
          rdfsLabel: 'Headway',
          skosDefinition: 'A measure of the distance between vehicles on the network.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        903: {
          edgeId: 903,
          from: '90',
          id: '903',
          label: 'Issued through',
          rdfAbout: 'http://webprotege.stanford.edu/R7dYrsdk1L1bcLR0A9vS5QP',
          rdfsLabel: 'Issued through',
          role: 'Issued through',
          to: '128',
          type: 'edge',
          userDefined: false,
        },
        92: {
          edgeId: 92,
          from: '9',
          id: '92',
          label: 'Implemented through',
          rdfAbout: 'http://webprotege.stanford.edu/RbjcXDTrplTouTeWRoMMe7',
          rdfsLabel: 'Implemented through',
          role: 'Implemented through',
          to: '27',
          type: 'edge',
          userDefined: false,
        },
        94: {
          'Business Area': 'Maintain Operate Plan',
          'Data Source': 'Confirm DDMS',
          id: '94',
          label: 'Environmental Incident',
          name: 'Environmental Incident',
          nodeId: 94,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/R9yaUi67502d49oMbx70wiF',
          rdfsLabel: 'Environmental Incident',
          skosDefinition: 'An unplanned time-bound event that occurs on or near Strategic Road Network Assets due to environmental factors such as flooding, poor water quality, pollution, etc.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        95: {
          'Business Area': 'Operate',
          id: '95',
          label: 'Patrol',
          name: 'Patrol',
          nodeId: 95,
          nodeType: 'class',
          rdfAbout: 'http://webprotege.stanford.edu/RB0lf4hZ1CRIjB3tldwNYlq',
          rdfsLabel: 'Patrol',
          skosDefinition: 'One or more Persons physically travelling around the Network for the purposes of Monitoring the Traffic (defined as Vehicles on Strategic Road Network Assets) and reacting to Incidents.',
          type: 'node',
          upperOntology: false,
          userDefined: false,
        },
        992: {
          edgeId: 992,
          from: '99',
          id: '992',
          label: 'Paid through',
          rdfAbout: 'http://webprotege.stanford.edu/RCO41EY55jxxkXEYAsRnzul',
          rdfsLabel: 'Paid through',
          role: 'Paid through',
          to: '27',
          type: 'edge',
          userDefined: false,
        },
      }
    )
  })
})
