/* eslint max-len:0 */
import structuredSearchElement from '../../../utils/structuredSearch/structuredSearchElement'
import { classesFromApi } from '../../fixtures/classesFromApi'
import { objectPropertiesFromApi } from '../../fixtures/objectPropertiesFromApi'
import store from '../../../store'
import getNodeIds from '../../../utils/nodesEdgesUtils/getNodeIds'
import getEdgeIds from '../../../utils/nodesEdgesUtils/getEdgeIds'

const setStoreState = jest.fn()

store.getState = jest.fn().mockImplementation(() => ({
  classesFromApi,
  objectPropertiesFromApi,
}))

jest.mock('../../../utils/nodesEdgesUtils/getNodeIds')
jest.mock('../../../utils/nodesEdgesUtils/getEdgeIds')

getNodeIds.mockImplementation(() => Object.keys(classesFromApi))
getEdgeIds.mockImplementation(() => Object.keys(objectPropertiesFromApi))

describe('structuredSearchElement', () => {
  afterEach(() => {
    jest.clearAllMocks()
  })

  it('should not call setStoreState when empty filters', async () => {
    const queryLogic = 'and'
    const filters = []

    await structuredSearchElement({
      filters,
      queryLogic,
      setStoreState,
    })

    expect(setStoreState).toHaveBeenCalledTimes(0)
  })

  it('should not call setStoreState when filters with no value', async () => {
    const queryLogic = 'and'
    const filters = [{
      property: 'rdfAbout',
      value: ''
    }, {
      property: 'rdfsLabel',
      value: ''
    }]

    await structuredSearchElement({
      filters,
      queryLogic,
      setStoreState,
    })

    expect(setStoreState).toHaveBeenCalledTimes(0)
  })

  it('should return correct results when AND query', async () => {
    const queryLogic = 'and'
    const filters = [{
      property: 'rdfsLabel',
      value: 'ro'
    }, {
      property: 'rdfsLabel',
      value: 'ad'
    }]

    await structuredSearchElement({
      filters,
      queryLogic,
      setStoreState,
    })

    expect(setStoreState).toHaveBeenCalledWith(
      'structuredSelection',
      {
        122: {
          'Business Area': 'Maintain Construct Operate Plan',
          'Data Source': 'MIDAS',
          Subdomain: 'MIDAS',
          id: '122',
          label: 'Roadside Operational Technology',
          nodeId: 122,
          rdfAbout: 'http://webprotege.stanford.edu/RCOdkBizz0dWtRTEjZSfqP8',
          rdfsLabel: 'Roadside Operational Technology',
          skosDefinition: 'Items involved in the digital capture, transfer, or analysis of information specifically related to the Strategic Road Network Asset.',
          skosExample: 'MIDAS Conduction Loop',
          type: 'node',
          userDefined: false,
        },
        180: {
          'Business Area': 'Maintain Construct',
          Subdomain: 'Construction phase',
          id: '180',
          label: 'Road Safety Measure',
          nodeId: 180,
          rdfAbout: 'http://webprotege.stanford.edu/Rigjqi5P4ZscabU1Pot3hK',
          rdfsLabel: 'Road Safety Measure',
          skosDefinition: 'Methods and measures used to prevent road users and workers from being killed or seriously injured.',
          type: 'node',
          userDefined: false,
        },
        70: {
          'Business Area': 'Maintain Plan Operate Construct Plan',
          Subdomain: 'Construction phase',
          id: '70',
          label: 'Strategic Road Network Asset',
          nodeId: 70,
          rdfAbout: 'http://webprotege.stanford.edu/R9H3QGGtwC0XhV4Mfk6Ceep',
          rdfsLabel: 'Strategic Road Network Asset',
          skosDefinition: 'Assets that, when combined, create and support the physical network of roads managed by the Licence Holder known as the Strategic Road Network Asset (which are represented by a Network Model).',
          type: 'node',
          userDefined: false,
        },
        99: {
          'Business Area': 'Maintain Construct Plan',
          id: '99',
          label: 'Road Restraint',
          nodeId: 99,
          rdfAbout: 'http://webprotege.stanford.edu/RBBDxx5ZaIbg5ASqGAeyKGg',
          rdfsLabel: 'Road Restraint',
          skosDefinition: 'Assets designed to contain, slow down, and stop errant vehicles, and to protect other Assets and Customers from errant Vehicles.',
          type: 'node',
          userDefined: false,
        },
      }
    )
  })

  it('should return correct results when OR query', async () => {
    const queryLogic = 'or'
    const filters = [{
      property: 'rdfsLabel',
      value: 'ro'
    }, {
      property: 'rdfsLabel',
      value: 'ad'
    }]

    await structuredSearchElement({
      filters,
      queryLogic,
      setStoreState,
    })

    expect(setStoreState).toHaveBeenCalledWith(
      'structuredSelection',
      {
        1033: {
          edgeId: 1033,
          from: '103',
          id: '1033',
          label: 'Advised by',
          rdfAbout: 'http://webprotege.stanford.edu/R7V7p8sdl5TpSs0cd7gZvqr',
          rdfsLabel: 'Advised by',
          role: 'Advised by',
          to: '122',
          type: 'edge',
          userDefined: false,
        },
        104: {
          'Business Area': 'Maintain Construct Plan',
          id: '104',
          label: 'Environmental',
          nodeId: 104,
          rdfAbout: 'http://webprotege.stanford.edu/RBKQgaabYcnNDy5hL7YKCKt',
          rdfsLabel: 'Environmental',
          skosComment: "Environmental is broadly split into three parts: Organisms (plants, animals, vegetation, grasslands), Cultural Heritage sites, and Noise Barriers. \"Environmental\" as a word seems to relate more closely with the Organisms meaning. As there are three distinct meanings, these were all defined separately and combined to create the overall definition of \"Environmental\" above. If either of the three areas get moved under a different heading (Entity) then the definitions can simply be cut and pasted into that new heading's (Entity's) definition.",
          skosDefinition: 'Plants, animals, and their habitats around the Strategic Road Network Asset; as well as Cultural Heritage and Art sites around the Strategic Road Network Asset; and Noise Barriers.',
          type: 'node',
          userDefined: false,
        },
        1051: {
          edgeId: 1051,
          from: '105',
          id: '1051',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '12',
          type: 'edge',
          userDefined: false,
        },
        1062: {
          edgeId: 1062,
          from: '106',
          id: '1062',
          label: 'Advised by',
          rdfAbout: 'http://webprotege.stanford.edu/R7V7p8sdl5TpSs0cd7gZvqr',
          rdfsLabel: 'Advised by',
          role: 'Advised by',
          to: '124',
          type: 'edge',
          userDefined: false,
        },
        1087: {
          edgeId: 1087,
          from: '108',
          id: '1087',
          label: 'Obtained through',
          rdfAbout: 'http://webprotege.stanford.edu/RDgkQlvQbb2skaXpfhIEAp8',
          rdfsLabel: 'Obtained through',
          role: 'Obtained through',
          to: '9',
          type: 'edge',
          userDefined: false,
        },
        110: {
          'Business Area': 'Construct',
          id: '110',
          label: 'Progress',
          nodeId: 110,
          rdfAbout: 'http://webprotege.stanford.edu/RBeMHRpPtIj9w4fNQv66hnI',
          rdfsLabel: 'Progress',
          skosDefinition: 'The degree of gradual improvement of a process or Project.',
          type: 'node',
          userDefined: false,
        },
        1141: {
          edgeId: 1141,
          from: '114',
          id: '1141',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '192',
          type: 'edge',
          userDefined: false,
        },
        12: {
          edgeId: 12,
          from: '1',
          id: '12',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '170',
          type: 'edge',
          userDefined: false,
        },
        122: {
          'Business Area': 'Maintain Construct Operate Plan',
          'Data Source': 'MIDAS',
          Subdomain: 'MIDAS',
          id: '122',
          label: 'Roadside Operational Technology',
          nodeId: 122,
          rdfAbout: 'http://webprotege.stanford.edu/RCOdkBizz0dWtRTEjZSfqP8',
          rdfsLabel: 'Roadside Operational Technology',
          skosDefinition: 'Items involved in the digital capture, transfer, or analysis of information specifically related to the Strategic Road Network Asset.',
          skosExample: 'MIDAS Conduction Loop',
          type: 'node',
          userDefined: false,
        },
        1221: {
          edgeId: 1221,
          from: '122',
          id: '1221',
          label: 'Controlled by',
          rdfAbout: 'http://webprotege.stanford.edu/R8XmPwbVWaRiEyUv3kxunaF',
          rdfsLabel: 'Controlled by',
          role: 'Controlled by',
          to: '53',
          type: 'edge',
          userDefined: false,
        },
        1222: {
          edgeId: 1222,
          from: '122',
          id: '1222',
          label: 'Controlled by',
          rdfAbout: 'http://webprotege.stanford.edu/R8XmPwbVWaRiEyUv3kxunaF',
          rdfsLabel: 'Controlled by',
          role: 'Controlled by',
          to: '192',
          type: 'edge',
          userDefined: false,
        },
        130: {
          'Business Area': 'Maintain Plan Operate Construct',
          id: '130',
          label: 'Carriageway Control',
          nodeId: 130,
          rdfAbout: 'http://webprotege.stanford.edu/RCrgRyMOzbaY6vxlnONgyzo',
          rdfsLabel: 'Carriageway Control',
          skosDefinition: 'Assets used to inform, direct, and control Traffic (Vehicles on the Strategic Road Network Asset) and form boundaries within the Strategic Road Network Asset.',
          skosExample: 'Post (Signs), Post (Traffic Signal), Block Wall, Fence, Cattle Grid',
          type: 'node',
          userDefined: false,
        },
        1391: {
          edgeId: 1391,
          from: '139',
          id: '1391',
          label: 'Performed from',
          rdfAbout: 'http://webprotege.stanford.edu/RC48Hic1INaQShlkSyb6ZIx',
          rdfsLabel: 'Performed from',
          role: 'Performed from',
          to: '84',
          type: 'edge',
          userDefined: false,
        },
        144: {
          'Business Area': 'Operate Design Construct Plan Communications',
          Subdomain: 'Handover',
          id: '144',
          label: 'Project Phase',
          nodeId: 144,
          rdfAbout: 'http://webprotege.stanford.edu/RDUwHG4VnwQTyDDhhsWSwgS',
          rdfsLabel: 'Project Phase',
          skosComment: 'The Project Control Framework is used in Major Projects and contains the stages: \n1. Strategy, Shaping and Prioritisation\n2. Option Identification\n3. Option selection\n4. Preliminary Design\n5. Statutory Procedures and Powers\n6. Construction Preparation\n7. Construction, Commissioning and Handover\n8. Closeout',
          skosDefinition: 'Goal-oriented collection of activities within a Project that ends at a milestone and are defined within a framework, where each phase can be divided into sub-phases.',
          skosExample: 'Pre-project, Options phase, Development phase, Construction phase',
          type: 'node',
          userDefined: false,
        },
        1442: {
          edgeId: 1442,
          from: '144',
          id: '1442',
          label: 'Controlled by',
          rdfAbout: 'http://webprotege.stanford.edu/R8XmPwbVWaRiEyUv3kxunaF',
          rdfsLabel: 'Controlled by',
          role: 'Controlled by',
          to: '183',
          type: 'edge',
          userDefined: false,
        },
        1463: {
          edgeId: 1463,
          from: '146',
          id: '1463',
          label: 'Paid through',
          rdfAbout: 'http://webprotege.stanford.edu/RCO41EY55jxxkXEYAsRnzul',
          rdfsLabel: 'Paid through',
          role: 'Paid through',
          to: '25',
          type: 'edge',
          userDefined: false,
        },
        1472: {
          edgeId: 1472,
          from: '147',
          id: '1472',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '170',
          type: 'edge',
          userDefined: false,
        },
        1475: {
          edgeId: 1475,
          from: '147',
          id: '1475',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '65',
          type: 'edge',
          userDefined: false,
        },
        1502: {
          edgeId: 1502,
          from: '150',
          id: '1502',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '128',
          type: 'edge',
          userDefined: false,
        },
        152: {
          edgeId: 152,
          from: '15',
          id: '152',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        161: {
          'Business Area': 'Maintain Design Plan Finance Operate Construct Communications',
          Subdomain: 'Pre-project phase, Construction phase',
          id: '161',
          label: 'Project',
          nodeId: 161,
          rdfAbout: 'http://webprotege.stanford.edu/RJVpffoomVWohIDaJCykd9',
          rdfsLabel: 'Project',
          skosDefinition: 'A time-bound undertaking of the Licence Holder (and Suppliers) to deliver a defined outcome to their organisation, stakeholders, or the general public.',
          skosExample: 'The road that needs to be built between the M25 and xyz in order to connect London to Inverness as part of a wider Programme.',
          type: 'node',
          userDefined: false,
        },
        1611: {
          edgeId: 1611,
          from: '161',
          id: '1611',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '164',
          type: 'edge',
          userDefined: false,
        },
        1612: {
          edgeId: 1612,
          from: '161',
          id: '1612',
          label: 'Proposed in',
          rdfAbout: 'http://webprotege.stanford.edu/R4I2v4Y7su3Adf0Vcj6TWd',
          rdfsLabel: 'Proposed in',
          role: 'Proposed in',
          to: '126',
          type: 'edge',
          userDefined: false,
        },
        1617: {
          edgeId: 1617,
          from: '161',
          id: '1617',
          label: 'Advised by',
          rdfAbout: 'http://webprotege.stanford.edu/R7V7p8sdl5TpSs0cd7gZvqr',
          rdfsLabel: 'Advised by',
          role: 'Advised by',
          to: '65',
          type: 'edge',
          userDefined: false,
        },
        177: {
          'Business Area': 'Maintain',
          id: '177',
          label: 'Product',
          nodeId: 177,
          rdfAbout: 'http://webprotege.stanford.edu/Rf8re1EdmLU47EIlLtCpzx',
          rdfsLabel: 'Product',
          skosDefinition: 'A software package that performs a specific function directly for an end user or, in some cases, for another Product.',
          type: 'node',
          userDefined: false,
        },
        1786: {
          edgeId: 1786,
          from: '178',
          id: '1786',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '67',
          type: 'edge',
          userDefined: false,
        },
        18: {
          id: '18',
          label: 'MetaData',
          nodeId: 18,
          rdfAbout: 'http://webprotege.stanford.edu/R7QCWoGMafG9zhjDYABQQgm',
          rdfsLabel: 'MetaData',
          skosDefinition: 'Data about data.',
          type: 'node',
          userDefined: false,
        },
        180: {
          'Business Area': 'Maintain Construct',
          Subdomain: 'Construction phase',
          id: '180',
          label: 'Road Safety Measure',
          nodeId: 180,
          rdfAbout: 'http://webprotege.stanford.edu/Rigjqi5P4ZscabU1Pot3hK',
          rdfsLabel: 'Road Safety Measure',
          skosDefinition: 'Methods and measures used to prevent road users and workers from being killed or seriously injured.',
          type: 'node',
          userDefined: false,
        },
        1822: {
          edgeId: 1822,
          from: '182',
          id: '1822',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '12',
          type: 'edge',
          userDefined: false,
        },
        184: {
          'Business Area': 'Operate Design Construct Plan Maintain',
          id: '184',
          label: 'Environmental Condition',
          nodeId: 184,
          rdfAbout: 'http://webprotege.stanford.edu/RmVBgJPMOQ5Amchla0VZUw',
          rdfsLabel: 'Environmental Condition',
          skosDefinition: 'A measure of how the environment proximate to the Network is developing or declining.',
          type: 'node',
          userDefined: false,
        },
        1842: {
          edgeId: 1842,
          from: '184',
          id: '1842',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        1852: {
          edgeId: 1852,
          from: '185',
          id: '1852',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '103',
          type: 'edge',
          userDefined: false,
        },
        186: {
          'Business Area': 'Maintain Operate',
          Subdomain: 'MIDAS',
          id: '186',
          label: 'Control Centre',
          nodeId: 186,
          rdfAbout: 'http://webprotege.stanford.edu/RnMK2vS5olvsw9Krge2Ymj',
          rdfsLabel: 'Control Centre',
          skosDefinition: 'A facility, used by the License Holder, which permits the coordinated and deliberate monitoring and regulation of service on the Network.',
          type: 'node',
          userDefined: false,
        },
        1894: {
          edgeId: 1894,
          from: '189',
          id: '1894',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '186',
          type: 'edge',
          userDefined: false,
        },
        1911: {
          edgeId: 1911,
          from: '191',
          id: '1911',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        1915: {
          edgeId: 1915,
          from: '191',
          id: '1915',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '12',
          type: 'edge',
          userDefined: false,
        },
        1922: {
          edgeId: 1922,
          from: '192',
          id: '1922',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '61',
          type: 'edge',
          userDefined: false,
        },
        1953: {
          edgeId: 1953,
          from: '195',
          id: '1953',
          label: 'Proposed in',
          rdfAbout: 'http://webprotege.stanford.edu/R4I2v4Y7su3Adf0Vcj6TWd',
          rdfsLabel: 'Proposed in',
          role: 'Proposed in',
          to: '144',
          type: 'edge',
          userDefined: false,
        },
        2: {
          'Business Area': 'Maintain Plan',
          id: '2',
          label: 'Programme',
          nodeId: 2,
          rdfAbout: 'http://webprotege.stanford.edu/R0qk59fxFmgNbyUncZoU8M',
          rdfsLabel: 'Programme',
          skosComment: 'A strategic goal that is achieved through a number of projects.',
          skosDefinition: 'A collection of projects or tasks undertaken to realise a strategic goal.',
          skosExample: 'Develop connectivity between London and Inverness.',
          type: 'node',
          userDefined: false,
        },
        212: {
          edgeId: 212,
          from: '21',
          id: '212',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '146',
          type: 'edge',
          userDefined: false,
        },
        32: {
          'Business Area': 'Operate',
          'Data Source': 'Confirm',
          Subdomain: 'Confirm',
          Synonym: 'Polyline',
          id: '32',
          label: 'Route',
          nodeId: 32,
          rdfAbout: 'http://webprotege.stanford.edu/R7pIV91w7fTKppAHSmrz8n',
          rdfsLabel: 'Route',
          skosDefinition: 'A potential way or course to get from one Node to another.',
          type: 'node',
          userDefined: false,
        },
        386: {
          edgeId: 386,
          from: '38',
          id: '386',
          label: 'Obtained through',
          rdfAbout: 'http://webprotege.stanford.edu/RDgkQlvQbb2skaXpfhIEAp8',
          rdfsLabel: 'Obtained through',
          role: 'Obtained through',
          to: '21',
          type: 'edge',
          userDefined: false,
        },
        452: {
          edgeId: 452,
          from: '45',
          id: '452',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        466: {
          edgeId: 466,
          from: '46',
          id: '466',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        492: {
          edgeId: 492,
          from: '49',
          id: '492',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        53: {
          'Business Area': 'Maintain Operate Design Finance Plan Communications',
          'Data Source': 'GIS RedLine Confirm',
          Subdomain: 'GIS RedLine, MIDAS, Options phase, Confirm',
          Type: 'Employee, External Staff, Administrator, Analyst, Internal Customer, Project Manager, Sponsor, User',
          id: '53',
          label: 'Role',
          nodeId: 53,
          rdfAbout: 'http://webprotege.stanford.edu/R8QQzkUbCD5WRXDQQSl0vX8',
          rdfsLabel: 'Role',
          skosDefinition: 'The function assumed or part played by a person or thing in a particular situation.',
          type: 'node',
          userDefined: false,
        },
        531: {
          edgeId: 531,
          from: '53',
          id: '531',
          label: 'Performed from',
          rdfAbout: 'http://webprotege.stanford.edu/RC48Hic1INaQShlkSyb6ZIx',
          rdfsLabel: 'Performed from',
          role: 'Performed from',
          to: '24',
          type: 'edge',
          userDefined: false,
        },
        603: {
          edgeId: 603,
          from: '60',
          id: '603',
          label: 'Operated from',
          rdfAbout: 'http://webprotege.stanford.edu/RvMCpTSGsQmEAyy8Mi6fdN',
          rdfsLabel: 'Operated from',
          role: 'Operated from',
          to: '186',
          type: 'edge',
          userDefined: false,
        },
        691: {
          edgeId: 691,
          from: '69',
          id: '691',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '65',
          type: 'edge',
          userDefined: false,
        },
        693: {
          edgeId: 693,
          from: '69',
          id: '693',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '192',
          type: 'edge',
          userDefined: false,
        },
        696: {
          edgeId: 696,
          from: '69',
          id: '696',
          label: 'Provided to',
          rdfAbout: 'http://webprotege.stanford.edu/RXaMAxdkuV5CvgEpovEVvp',
          rdfsLabel: 'Provided to',
          role: 'Provided to',
          to: '192',
          type: 'edge',
          userDefined: false,
        },
        697: {
          edgeId: 697,
          from: '69',
          id: '697',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '114',
          type: 'edge',
          userDefined: false,
        },
        70: {
          'Business Area': 'Maintain Plan Operate Construct Plan',
          Subdomain: 'Construction phase',
          id: '70',
          label: 'Strategic Road Network Asset',
          nodeId: 70,
          rdfAbout: 'http://webprotege.stanford.edu/R9H3QGGtwC0XhV4Mfk6Ceep',
          rdfsLabel: 'Strategic Road Network Asset',
          skosDefinition: 'Assets that, when combined, create and support the physical network of roads managed by the Licence Holder known as the Strategic Road Network Asset (which are represented by a Network Model).',
          type: 'node',
          userDefined: false,
        },
        701: {
          edgeId: 701,
          from: '70',
          id: '701',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        709: {
          edgeId: 709,
          from: '70',
          id: '709',
          label: 'Obtained through',
          rdfAbout: 'http://webprotege.stanford.edu/RDgkQlvQbb2skaXpfhIEAp8',
          rdfsLabel: 'Obtained through',
          role: 'Obtained through',
          to: '9',
          type: 'edge',
          userDefined: false,
        },
        71: {
          edgeId: 71,
          from: '7',
          id: '71',
          label: 'Improved through',
          rdfAbout: 'http://webprotege.stanford.edu/R8fzvBl85R2Nc2SqsikiKp9',
          rdfsLabel: 'Improved through',
          role: 'Improved through',
          to: '161',
          type: 'edge',
          userDefined: false,
        },
        732: {
          edgeId: 732,
          from: '73',
          id: '732',
          label: 'Provided by',
          rdfAbout: 'http://webprotege.stanford.edu/RCptIcn975cERAVUlJOL7sV',
          rdfsLabel: 'Provided by',
          role: 'Provided by',
          to: '103',
          type: 'edge',
          userDefined: false,
        },
        742: {
          edgeId: 742,
          from: '74',
          id: '742',
          label: 'Implemented through',
          rdfAbout: 'http://webprotege.stanford.edu/RbjcXDTrplTouTeWRoMMe7',
          rdfsLabel: 'Implemented through',
          role: 'Implemented through',
          to: '176',
          type: 'edge',
          userDefined: false,
        },
        76: {
          'Business Area': 'Maintain Design Finance Construct',
          id: '76',
          label: 'Project Document',
          nodeId: 76,
          rdfAbout: 'http://webprotege.stanford.edu/R9WIxkbvxYbhp8NthzYsXSx',
          rdfsLabel: 'Project Document',
          skosDefinition: 'Document related to the running of a Project.',
          skosExample: 'Project Control Document',
          type: 'node',
          userDefined: false,
        },
        81: {
          'Business Area': 'Operate',
          'Data Source': 'MIDAS',
          Subdomain: 'MIDAS',
          id: '81',
          label: 'Headway',
          nodeId: 81,
          rdfAbout: 'http://webprotege.stanford.edu/R9r0DVvDkFW6GmN4bDUNsyl',
          rdfsLabel: 'Headway',
          skosDefinition: 'A measure of the distance between vehicles on the network.',
          type: 'node',
          userDefined: false,
        },
        871: {
          edgeId: 871,
          from: '87',
          id: '871',
          label: 'Issued through',
          rdfAbout: 'http://webprotege.stanford.edu/R7dYrsdk1L1bcLR0A9vS5QP',
          rdfsLabel: 'Issued through',
          role: 'Issued through',
          to: '122',
          type: 'edge',
          userDefined: false,
        },
        91: {
          'Business Area': 'Maintain Operate Plan',
          id: '91',
          label: 'Environmental Incident',
          nodeId: 91,
          rdfAbout: 'http://webprotege.stanford.edu/R9yaUi67502d49oMbx70wiF',
          rdfsLabel: 'Environmental Incident',
          skosDefinition: 'An unplanned time-bound event that occurs on or near Strategic Road Network Assets due to environmental factors such as flooding, poor water quality, pollution, etc.',
          type: 'node',
          userDefined: false,
        },
        92: {
          edgeId: 92,
          from: '9',
          id: '92',
          label: 'Implemented through',
          rdfAbout: 'http://webprotege.stanford.edu/RbjcXDTrplTouTeWRoMMe7',
          rdfsLabel: 'Implemented through',
          role: 'Implemented through',
          to: '25',
          type: 'edge',
          userDefined: false,
        },
        99: {
          'Business Area': 'Maintain Construct Plan',
          id: '99',
          label: 'Road Restraint',
          nodeId: 99,
          rdfAbout: 'http://webprotege.stanford.edu/RBBDxx5ZaIbg5ASqGAeyKGg',
          rdfsLabel: 'Road Restraint',
          skosDefinition: 'Assets designed to contain, slow down, and stop errant vehicles, and to protect other Assets and Customers from errant Vehicles.',
          type: 'node',
          userDefined: false,
        },
      }
    )
  })
})
